spring:
  freemarker:
    suffix: .ftl  #加载后缀
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/table?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: mysql159612
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update #如果这里是create，则在每次更新后台之后，数据库中的内容都会被清空
    show-sql: true
    open-in-view: false
  server: #配置应用名
    servlet:
      context-path:/sell
